import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid items-center flex flex-col justify-center align-middle p-10 h-screen">
        <div className="container mx-auto text-center text-7xl font-bold opacity-90 p-4 md:text-8xl">
          VIKAMARA CLOTHING
        </div>
        <div className="text-4xl font-semibold">
          Affordable Luxury
        </div>
      </div>
    </>
  )
}
